# Generated by Django 5.2.12 on 2026-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
